/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import edu.austral.dissis.commons.GameEngineImpl
import edu.austral.dissis.chess.gui.*
import edu.austral.dissis.server.ChessMoveListener
import edu.austral.dissis.server.ClientConnectionCollectorListener
import edu.austral.dissis.server.MessageCollectorListener
import edu.austral.dissis.server.ServerConnectionCollectorListener
import edu.austral.ingsis.clientserver.*
import edu.austral.ingsis.clientserver.netty.client.NettyClientBuilder
import edu.austral.ingsis.clientserver.netty.server.NettyServerBuilder
import javafx.application.Application
import javafx.application.Application.launch
import javafx.scene.Scene
import javafx.stage.Stage
import java.net.InetSocketAddress


fun main() {
    launch(ChessGameApplication::class.java)
}

class ChessGameApplication : Application() {
    val gameEngine = GameEngineImpl.withCheckersRules()
    private val imageResolver = CachedImageResolver(DefaultImageResolver())


    companion object {
        const val GameTitle = "Chess"
    }

    override fun start(primaryStage: Stage) {
        primaryStage.title = GameTitle
        val root = createGameViewFrom(gameEngine, imageResolver)
        primaryStage.scene = Scene(root)
        root.handleInitialState(gameEngine.init())
        primaryStage.show()

    }
}